apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: customer:main # Replace with your image and tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: CUSTOMER_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key: .env.dev
          # Add volume mounts and resources as needed
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"  # Adjust the CPU limit as needed
            requests:
              cpu: "100m"  # Adjust the CPU request as needed
      # imagePullSecrets:
      #   - name: regcred