apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  selector:
    app: nginx-proxy
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 80
  type: LoadBalancer  # or NodePort
  ports:
    - port: 80        # Service port
      targetPort: 80