# Promote-container-stg:
#   stage: Release-stg
#   tags:
#     - dostream
#   services:
#     - name: docker:dind
#   image: docker:latest
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - VERSION=$(cat version.txt)-stg
#     - export STG_IMAGE_NAME="$CI_REGISTRY:$CI_COMMIT_REF_NAME-$VERSION"
#     - echo $STG_IMAGE_NAME > my_variable_stg.txt
#     - IMAGE_NAME=$(cat my_variable.txt)
#     - docker pull $IMAGE_NAME
#     - docker tag $IMAGE_NAME $STG_IMAGE_NAME
#     - docker push $STG_IMAGE_NAME
#   needs:
#     - job: notification_email_dev
#   artifacts:
#     paths:
#       - my_variable_stg.txt

Promote-container-stg:
  stage: Release-stg
  tags:
    - dostream
  services:
    - name: docker:dind
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - VERSION_STG=$(cat version.txt)-stg
    - export STG_IMAGE_NAME="$CI_REGISTRY:$VERSION_STG"
    - echo $STG_IMAGE_NAME > my_variable_stg.txt
    - IMAGE_NAME=$(cat my_variable_dev.txt)
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $STG_IMAGE_NAME
    - docker push $STG_IMAGE_NAME
  needs:
    - job: Promote-container-dev
      artifacts: true
    - job: notification_email_dev
  artifacts:
    paths:
      - my_variable_stg.txt


# Release for dev environment 
generate_tag_stg:
  stage: Release-stg
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when the default branch changes
  script:
    - VERSION=$(cat version.txt)-stg
    - echo "TAG=$VERSION" > tag.env
  artifacts:
    reports:
      dotenv: tag.env
  needs:
    - job: Promote-container-stg

auto-release-master_stg:
  stage: Release-stg
  image: registry.gitlab.com/gitlab-org/release-cli
  needs:
    - job: generate_tag_stg
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed to the default branch
  script:
    - echo "Release $TAG"
    - release-cli --server-url https://gitlab.com --project-id 51551547 --private-token $CI_JOB_TOKEN create --name "Release $TAG" --description "Created using the release-cli $EXTRA_DESCRIPTION" --tag-name "V$TAG"  --ref $CI_COMMIT_SHA


#Deploying in Dev
Deploy-stg:
  stage: Stg-Deploy
  tags:
    - dostream
  when: manual
  script:
    - echo "Running stg deploy..."
    # Run your smoke tests here
  needs:
    - job: Promote-container-dev
      artifacts: true
    - job: auto-release-master_stg

unit-test_stg:
  stage: Tests-stg
  script:
    - echo "Running smoke tests..."
    # Run your smoke tests here
  needs:
    - job: Deploy-stg

Shadow-test_stg:
  stage: Tests-stg
  script:
    - echo "Running Shadow tests..."
    # Run your smoke tests here
  needs:
    - job: Deploy-stg

Integration-test_stg:
  stage: Tests-stg
  script:
    - echo "Running Integration tests..."
    # Run your smoke tests here
  needs:
    - job: Deploy-stg

Load-test_stg:
  stage: Tests-stg
  script:
    - echo "Running load tests..."
    # Run your smoke tests here
  needs:
    - job: Deploy-stg

End-user-test_stg:
  stage: Tests-stg
  script:
    - echo "Running end-user tests..."
    # Run your smoke tests here
  needs:
    - job: Deploy-stg


notification_email_stg:
  stage: Notification-stg
  script:
    - echo "Running notification send"
    # Run your smoke tests here
  # needs:
  #   - job: Deploy-Dev
#actual code below
# notification_email:
#   stage: Notify
#   image: alpine:latest
#   variables:
#     EMAIL_LIST: "recipient1@example.com recipient2@example.com recipient3@example.com"
#   script:
#     - apk add --no-cache mailx
#     - |
#       for email in $EMAIL_LIST; do
#         echo "Your pipeline has completed successfully!" | mailx -s "Pipeline Notification" "$email"
#       done
#   only:
#     - master
  needs:
    - job: unit-test_stg
    - job: Shadow-test_stg
    - job: Integration-test_stg
    - job: Load-test_stg
    - job: End-user-test_stg
