apiVersion: v1
kind: Service
metadata:
  name: nosql-db-service
spec:
  selector:
    app: nosql-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
# spec:
#   selector:
#     app: mongodb
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017