apiVersion: v1
spec:
  containers:
    - name: copy-container
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "cp -r /source/. /destination/"]
      volumeMounts:
        - name: data
          mountPath: /destination/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc
